### PR TITLE
add Sepolia testnet, remove confusing NftMetadata in NearNftService

### PR DESCRIPTION
**Pull request by Lan-Phan**
Hello,

I have this PR with these changes below:
1. Add new testnet Sepolia, just because Goerli is really difficult for newbie to get faucet and it'll be shutdown at the end of this year
2. I see that data class NftMetadata in NearNftService cause projects using nftkit confused (currently there are 2 NftMetadata in services package, 1 in NearNftService and the other in NftService), even testing cannot be compiled. I think the one in NearNftService is not correct and not needed, please double check.

### CODE REVIEW

**Review by SuperBatata — COMMENTED** [review]
LGTM

**Comment by taminobaumann** [comment]
> LGTM

Thanks for the review!

**Comment by Lan-Phan** [comment]
Hello @taminobaumann 

Thanks for merging. Do you have plan to publish this change with new nft-kit version (also new waltid-siwe version too)?

**Comment by taminobaumann** [comment]
Hey @Lan-Phan, 
we release continuously with every pull request that gets merged, see [latest releases](https://github.com/walt-id/waltid-nftkit/releases). Currently, we don't have a new release plant for waltid-siwe. Why do you ask?

**Comment by Lan-Phan** [comment]
Hi @taminobaumann ,

The reason is that, when I tried my code locally, if I doesn't build waltid-siwe again, waltid-idpkit doesn't recognize sepolia configure.

Let I double check again with your new build, thanks.

**Comment by taminobaumann** [comment]
@SuperBatata, does the IDP-Kit also hold own references of the supported blockchains or does it get the supported blockchains directly from the NFT-Kit?

**Comment by Lan-Phan** [comment]
Hi @taminobaumann ,

I confirm that we don't need new build of waltid-siwe to use this update in idpkit, I just change version of nftkit to the new one, build again and it works.

Thanks.

**Pull request merged**
